name: Terraform Security Scan

on:
  push:
    paths:
      - '**.tf'
      - '.github/workflows/terraform-scan.yml'
  pull_request:
    paths:
      - '**.tf'
      - '.github/workflows/terraform-scan.yml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  security-scan:
    name: Terraform Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terrascan
        run: |
          curl -L "$(curl -s https://api.github.com/repos/accurics/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
          tar -xf terrascan.tar.gz terrascan
          rm terrascan.tar.gz
          sudo install terrascan /usr/local/bin
          rm terrascan

      - name: Run Terrascan (Basic Scan)
        id: terrascan-basic
        run: |
          # Run initial scan and save results
          terrascan scan \
            -t gcp \
            -i terraform \
            -d . \
            -o json > terrascan-results.json
          
          # Also generate human-readable output
          terrascan scan \
            -t gcp \
            -i terraform \
            -d . \
            -o human | tee terrascan-human.txt
            
          # Generate SARIF output
          terrascan scan \
            -t gcp \
            -i terraform \
            -d . \
            -o sarif > terrascan.sarif || true
            
          # Verify SARIF file is valid JSON
          if ! jq empty terrascan.sarif 2>/dev/null; then
            echo "SARIF file is invalid or empty, creating a minimal valid SARIF file"
            echo '{"version":"2.1.0","$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","runs":[{"tool":{"driver":{"name":"terrascan","informationUri":"https://github.com/accurics/terrascan","rules":[]}},"results":[]}]}' > terrascan.sarif
          fi
        continue-on-error: true

      - name: Run Advanced Security Checks
        id: advanced-checks
        run: |
          # Run additional security checks for high severity issues
          # Note: Using --severity-level instead of --severity
          terrascan scan \
            -t gcp \
            -i terraform \
            -d . \
            --severity-level high \
            -o json > high-severity-results.json
          
          # Parse results and set output
          HIGH_COUNT=$(jq '.violations | map(select(.severity == "HIGH")) | length' terrascan-results.json)
          MEDIUM_COUNT=$(jq '.violations | map(select(.severity == "MEDIUM")) | length' terrascan-results.json)
          echo "high_severity_count=$HIGH_COUNT" >> $GITHUB_ENV
          echo "medium_severity_count=$MEDIUM_COUNT" >> $GITHUB_ENV
        continue-on-error: true

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: terraform-scan-results
          path: |
            terrascan-results.json
            terrascan-human.txt
            high-severity-results.json
            terrascan.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terrascan.sarif

      - name: Check Results and Fail if Necessary
        run: |
          echo "Summary of findings:"
          echo "High severity issues: ${{ env.high_severity_count }}"
          echo "Medium severity issues: ${{ env.medium_severity_count }}"
          
          if [ "${{ env.high_severity_count }}" -ge 4 ]; then
            echo "❌ Failed: 4 or more high severity issues found!"
            exit 1
          elif [ "${{ env.high_severity_count }}" -gt 0 ]; then
            echo "⚠️ Warning: High severity issues found, but fewer than 4"
          fi
          
          if [ "${{ env.medium_severity_count }}" -gt 5 ]; then
            echo "⚠️ Warning: More than 5 medium severity issues found"
          fi
          
          echo "✅ Security scan passed!"